INSERT INTO assets (symbol, name, asset_type, currency, unit)
VALUES 
    ('AAPL', 'Apple', 'stock', 'USD', 'share'),
    ('MSFT', 'Microsoft', 'stock', 'USD', 'share'),
    ('NVDA', 'Nvidia', 'stock', 'USD', 'share'),
    ('TSLA', 'Tesla', 'stock', 'USD', 'share'),
    ('GOOGL', 'Google', 'stock', 'USD', 'share'),
    ('', 'S%P500', 'fond', 'USD', 'share'),
    ('', 'MSCI World', 'fond', 'USD', 'share'),
    ('', 'MSCI EM', 'fond', 'USD', 'share'),
    ('', 'Wheat', 'comm', 'USD', 'ton'),
    ('', 'Soy', 'comm', 'USD', 'ton'),
    ('', 'Corn', 'comm', 'USD', 'ton'),
    ('', 'Crude Oil', 'comm', 'USD', 'barrel'),
    ('XAU', 'Gold', 'comm', 'USD', 'ounce'),
    ('XAG', 'Silver', 'comm', 'USD', 'ounce'),
    ('XPT', 'Platinum', 'comm', 'USD', 'ounce'),
    ('BTC', 'Bitcoin', 'crypto', 'USD', 'BTC'),
    ('ETH', 'Ethereum', 'crypto', 'USD', 'ETH'),
    ('BNB', 'Binance Coin', 'crypto', 'USD', 'BNB'),
    ('XRP', 'Ripple', 'crypto', 'USD', 'XRP'),
    ('ADA', 'Cardano', 'crypto', 'USD', 'ADA'),
    ('DOT', 'Polkadot', 'crypto', 'USD', 'DOT'),
    ('DOGE', 'Dogecoin', 'crypto', 'USD', 'DOGE'),
    ('SOL', 'Solana', 'crypto', 'USD', 'SOL'),
    ('LTC', 'Litecoin', 'crypto', 'USD', 'LTC'),
    ('UNI', 'Uniswap', 'crypto', 'USD', 'UNI'),
    ('LINK', 'Chainlink', 'crypto', 'USD', 'LINK'),
    ('ATOM', 'Cosmos', 'crypto', 'USD', 'ATOM'),
    ('FTT', 'FTX Token', 'crypto', 'USD', 'FTT'),
    ('AVAX', 'Avalanche', 'crypto', 'USD', 'AVAX'),
    ('SHIB', 'Shiba Inu', 'crypto', 'USD', 'SHIB'),
    ('MATIC', 'Polygon', 'crypto', 'USD', 'MATIC'),
    ('TRX', 'TRON', 'crypto', 'USD', 'TRX'),
    ('WBTC', 'Wrapped Bitcoin', 'crypto', 'USD', 'WBTC'),
    ('DAI', 'Dai', 'crypto', 'USD', 'DAI'),
    ('FIL', 'Filecoin', 'crypto', 'USD', 'FIL'),
    ('VET', 'VeChain', 'crypto', 'USD', 'VET');
